# Generated by Django 5.2.17 on 2026-08-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_patronsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronsession',
            name='analytics_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patronsession',
            name='consent_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
