# Generated by Django 5.2.17 on 2026-08-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_patronsession_analytics_opt_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'placed'), ('preparing', 'preparing'), ('ready', 'ready'), ('served', 'served'), ('declined', 'declined')], default='placed', max_length=16),
        ),
    ]
