# Generated by Django 5.2.16 on 2026-07-16 02:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('table_number', models.CharField(max_length=32)),
                ('request_type', models.CharField(choices=[('call_server', 'call_server'), ('water', 'water'), ('check', 'check'), ('surprise_me', 'surprise_me')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('acknowledged', 'acknowledged'), ('resolved', 'resolved')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
